[package]
name = "tap"
version = "0.1.0"
authors = ["pierre <dommerc.pierre@gmail.com>"]
edition = "2018"
license = "MPL-2.0"
description = "a tiny argument parser for cli"
keywords = ["cli", "rust"]
categories = ["command-line-utilities"]


[dependencies]
regex = "1"
